from binascii import unhexlify
from riscvm.emulator import Emulator

def test_empty():
    data = unhexlify('9307f5ff00000000')
    Emulator(data).run()

def test_fib():
    '''
    test data is generated by riscv64-unknown-linux-gnu-gcc with march=rv64g
    and riscv64-unknown-linux-gnu-objcopy -O binary
    then hexlified by python binascii.hexlify()
    '''
    data = unhexlify('9307f5ff6354a00213071000930600001306f0ff130507009387f7ff3307d70093060500e398c7fe678000001305000067800000')
    Emulator(data).run()
